[package]
name = "couchbase-sys"
version = "0.4.0" # remember to update html_root_url
authors = ["Michael Nitschinger <michael.nitschinger@couchbase.com>"]
build = "build.rs"
links = "libcouchbase"
license = "Apache-2.0"
keywords = ["couchbase", "database", "ffi", "libcouchbase"]
categories = ["database", "asynchronous", "external-ffi-bindings"]
description = "Rust bindings to the libcouchbase C Couchbase SDK."
repository = "https://github.com/couchbaselabs/couchbase-rs"
homepage = "https://github.com/couchbaselabs/couchbase-rs"
documentation = "https://docs.rs/couchbase-sys"

[features]
default = ["build-lcb"]
generate-binding = ["bindgen"]
build-lcb = ["cmake"]

[build-dependencies]
pkg-config = "0.3"
bindgen =  { version = "0.30", optional = true }
cmake = { version  = "0.1", optional = true }

[lib]
doctest = false
